### ISSUE TITLE
Warning about router in console

### ISSUE THREAD

**Issue by jonaskello** [capaj/jspm-react#4]
When I run this as-is in Chrome I get this in the console:

```
Warning: You cannot change <Router routes>; it will be ignored
```

It seems to work anyway but would be nice to get rid of the warning.

**Comment by capaj** [comment]
yeah, this is something I started to get as well. Will definitely investigate when I have time.

**Comment by fryck** [comment]
+1 ...

**Comment by grady-lad** [comment]
I was coming across this today too, it seemed to not like forceUpdate() within the RenderForcer class.
I can still hot-reload by removing forceUpdate() but I still need this
class to perform hot reloads which has confused me more.

```

class RenderForcer extends Component {

  constructor() {
    super();
  }

  componentWillMount() {
    // this.forceUpdate();
  }

  render() {
    return (
      <Provider store={store}>
        <div>
        <Router history={createBrowserHistory()}>
          {getRoutes()}
        </Router>
        <DevTools/>
        </div>
      </Provider>
    );
  }
}

if (__DEVTOOLS__) {
  ReactDOM.render(
    <RenderForcer/>,
    document.getElementById('app')
  );
}
```

**Comment by dmi3y** [comment]
Based on this [comment](https://github.com/reactjs/react-router/issues/2704#issuecomment-174067923).

I did modify the `app.js` like so (moved Route from render Router into top level constant):

``` jsx
    import React from 'react'
    import ReactDOM from 'react-dom'
    import { browserHistory } from 'react-router'
    import { Router, Route } from 'react-router'

    import Home from './routes/home'
    import { IntlProvider, addLocaleData } from 'react-intl'
    import en from 'react-intl/locale-data/en'
    addLocaleData(en)

    const routes = <Route path='/' component={Home}/>

    class RenderForcer extends React.Component {
      constructor () {
        super()
      }
      componentWillMount () {
        this.forceUpdate()  // a little hack to help us rerender when this module is reloaded
      }
      render () {

        return <IntlProvider locale='en'>
          <Router history={browserHistory}>
            {routes}
          </Router>
        </IntlProvider>
      }
    }

    ReactDOM.render((
      <RenderForcer/>
    ), document.getElementById('app'))
```

Which made error (warning) goes away.

Also it seems makes sense to [separate routes](https://github.com/reactjs/react-router/issues/2704#issuecomment-170940448). Either way, if this is something that considered as improvement I can open MR.

**Comment by capaj** [comment]
@dmi3y  I did it already, thanks so much!
