### ISSUE TITLE
local installation of jspm, upgrade to jspm 0.17

### ISSUE THREAD

**Issue by davis** [capaj/jspm-react#7]
I had issues with postinstall because it seems like jspm must be installed globally.

Upgraded the repo to be 0.17 conformant, I could make a pull request if that would be useful!

Awesome repo!

**Comment by capaj** [comment]
@davis yeah, I should add jspm into devDependencies.
Regarding 0.17.0, I will convert it once 0.17 is released. Currently it is still beta.

**Comment by jntn** [comment]
@davis I'm interested in your upgraded version, could you check it in somewhere? :)

**Comment by capaj** [comment]
@jntn 0.17 version is available here on 0.17 branch if you're still interested.
